name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

#      - name: Build
#        run: npm run build:prod

      - name: Deploy to GitHub Pages using angular-cli-ghpages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run ng -- deploy --base-href=https://beligh-hamdi.github.io/tools/ --name="beligh-hamdi" --email=beligh.hamdi@gmail.com
        #  npm run deploy


#      - name: Deploy GitHub Pages using  GitHub Actions
#        if: success()
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: dist/beligh-tools/browser
#          enable_jekyll: true
