name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Config
        run: |
          git config --global user.email "beligh.hamdi@gmail.com"
          git config --global user.name "beligh-hamdi"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Copy index.html to 404.html
        run: cp dist/beligh-tools/browser/index.html dist/beligh-tools/browser/404.html

#      - name: Deploy to GitHub Pages (using angular-cli-ghpages)
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: npm run deploy


      - name: Deploy GitHub Pages using  GitHub Actions
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/beligh-tools/browser
          enable_jekyll: true
