name: GitHub Pages

on:
  push:
    branches:
      - main

env:
  USER_EMAIL: beligh.hamdi@gmail.com
  USER_NAME: beligh-hamdi
  USER_EMAIL_BOT: github-actions-bot@noreply.gmail.com
  USER_NAME_BOT: github-actions-bot
  APPLICATION_NAME: @beligh/tools
  PUBLISH_DIR: dist/${{ env.APPLICATION_NAME }}/browser
  WORK_RUNNER_DIR: /home/runner/work/tools/tools/

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Config
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Copy index.html to 404.html
        run: |
          cd ${{ env.WORK_RUNNER_DIR }} + ${{ env.PUBLISH_DIR }}
          cp index.html 404.html

#      - name: Deploy to GitHub Pages (using angular-cli-ghpages)
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: npm run deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $PUBLISH_DIR
          enable_jekyll: true
          user_name: "${{ env.USER_NAME_BOT }}"
          user_email: "${{ env.USER_EMAIL_BOT }}"
